sudo: false
cache:
  directories:
    - /home/travis/.theano
branches:
  only:
    - master
language: python
matrix:
  include:
    - python: 2.7
before_install:
  - # Setup Python environment with BLAS libraries
  - |
      if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
         wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
      else
         wget -q http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
      fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update -q --yes conda
install:
  # Install all Python dependencies
  - conda install -q --yes python=$TRAVIS_PYTHON_VERSION --file req-travis-conda.txt
  - pip install -q -r req-travis-pip.txt
script:
  # - pip install -e . -r requirements.txt # Tests setup.py
  - python potato.py
